article addressing performance concerns with the current schema
trolie/spec pull request #112
Opened 2024-06-23 01:55 UTC by catkins-miso

2024-06-23 20:29 UTC, getorymckeag requested changes
This is good.  I left some minor comments, but I also feel like you could lean into our expected interop problems a bit.  You don't have to lay it all our here, but we've designed intentional verbosity in this protocol in a couple of areas.  You already talked about the issues around periods, but I was thinking about the following:
- Model mismatches, naming convention mismatches (big one)
- Differences in units
- Differences in forecast windows.

2024-06-23 20:29 UTC, getorymckeag commented on docs/articles/tradeoffs.md
> +* Discussing the relative priority of certain quality attributes in the TROLIE
I worry a little about this bullet because I don't feel like the term "quality attribute" is really in most technologists vocabulary.   It's very much a term of the CMU doctrine.  To be clear, I understand it, and what you're saying is precise, but I worry it will go over most readers heads.

2024-06-23 20:29 UTC, getorymckeag commented on docs/articles/tradeoffs.md
> +("SAX-style" for you XML aficionados) parser when reading submissions. This
I suggest changing this parenthesis to ("SAX-style" in XML parlance).  It might be just me, but when I read aficionados it felt cringy.

2024-06-24 15:28 UTC, catkins-miso commented
> * Model mismatches, naming convention mismatches (big one)
I addressed this here https://github.com/trolie/spec/pull/112/files#diff-f5365834c7ab49f74bc2e501af580fcc2edee6ece91b70f670938973d80f4725R162

> * Differences in units
I believe this was previously addressed in https://github.com/trolie/spec/pull/112/files#diff-f5365834c7ab49f74bc2e501af580fcc2edee6ece91b70f670938973d80f4725R106

> * Differences in forecast windows.
https://github.com/trolie/spec/pull/112/files#diff-f5365834c7ab49f74bc2e501af580fcc2edee6ece91b70f670938973d80f4725R166

2024-06-24 15:30 UTC, catkins-miso commented
I'm going to merge this as I believe I've addressed the requested changes. I'm going to solicit feedback from a few individuals, so I'd like to get this out there and easy legible on trolie.energy

2024-06-24 15:30 UTC, merged