elaborate versioning strategy
trolie/spec pull request #210
Opened 2024-11-08 18:20 UTC by catkins-miso

closes #204

2024-11-14 13:38 UTC, catkins-miso commented
change language to "supporting *incremental* conformance" as opposed to *partial*

2024-11-14 13:39 UTC, catkins-miso commented on docs/decision-log/media-type-versioning.md
> +implementors, not the other way around; interop is the goal, not conformance.
```suggestion
implementors, not the other way around; interop is the goal, not blind conformance.
```

2024-11-14 13:39 UTC, catkins-miso commented on docs/decision-log/media-type-versioning.md
> +supported by different implementations.
```suggestion
supported by different implementations, supporting incremental conformance.
```

2024-11-14 13:40 UTC, catkins-miso commented on docs/decision-log/media-type-versioning.md
> +project's original charter.
```suggestion
project's original charter, with the goal of supporting incremental conformance.
```

2024-11-15 17:32 UTC, getorymckeag requested changes
This is pretty well thought through.  If you have a chance, I say just fix the links.

2024-11-15 17:32 UTC, getorymckeag commented on docs/decision-log/media-type-versioning.md
> +[Scope](https://github.com/trolie/spec/blob/1.0.0-wip/Scope.md).  Paramount to
You're going to want to make these links relative so they don't die when you change the branch name.

2024-11-15 17:54 UTC, catkins-miso commented on docs/decision-log/media-type-versioning.md
> +[Scope](https://github.com/trolie/spec/blob/1.0.0-wip/Scope.md).  Paramount to
```suggestion
[Scope](https://github.com/trolie/spec/tree/HEAD/Scope.md).  Paramount to
```

2024-11-15 17:57 UTC, getorymckeag commented on docs/decision-log/media-type-versioning.md
> +specification](https://github.com/trolie/spec/blob/1.0.0-wip/Community_Specification_License.md)
```suggestion
specification](https://github.com/trolie/spec/blob/HEAD/Community_Specification_License.md)
```

2024-11-15 17:57 UTC, getorymckeag approved these changes

2024-11-15 17:59 UTC, merged