introduce forecast proposal status media type
trolie/spec pull request #80
Opened 2024-03-15 17:15 UTC by caindy

This has a number of implications discussed in and closes #74

2024-03-19 00:19 UTC, catkins-miso requested changes

2024-03-19 00:19 UTC, catkins-miso commented on docs/_data/components/schemas/array-max-monitored-elements.yaml
> +        ⚠️ **The Ratings Provider should assert that this value is zero when they
```suggestion
        ⚠️ **The Ratings Provider should check that this value is zero when they
```

2024-03-19 00:20 UTC, catkins-miso approved these changes

2024-03-20 21:10 UTC, catkins-miso commented on docs/_data/paths/rating-proposals_forecasts.yaml
> +    Note that the same status object is returned in each
```suggestion
    Note that the same status object is returned for each
```

2024-03-20 21:11 UTC, catkins-miso commented on docs/_data/paths/rating-proposals_forecasts.yaml
> +    an anticipated use cases for this `GET` endpoint are to allow supervisor
```suggestion
    an anticipated use case for this `GET` endpoint is to allow supervisor
```

2024-03-20 21:12 UTC, catkins-miso commented on docs/_data/paths/rating-proposals_forecasts.yaml
> +    processes that are setup to independently ensure the provider's program for
```suggestion
    processes that are setup by the client to independently ensure the provider's process for
```

2024-03-21 19:17 UTC, getorymckeag approved these changes
OK, looks good.  Just to be clear, while I don't have any critical comments, I did some due diligence with our devs on this one.  I think it solves a number of problems well.

2024-03-21 19:18 UTC, merged